server:
  port: 8082
spring:
  application:
    name: category_service
  jpa:
    show-sql: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  profiles:
    active:
    - "@profileActive@"
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: "*"