spring:
  datasource:
    url: ${LOCATION_DB_URL}
    username: ${LOCATION_DB_USER}
    password: ${LOCATION_DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
