spring:
  cloud:
    gateway:
        routes:
        - id: business_service
          uri: http://localhost:8081
          predicates:
          - Path=/businesses/**
          filters:
          - name: CircuitBreaker
            args:
              name: fallback
              fallbackUri: forward:/fallback
        - id: category_service
          uri: http://localhost:8082
          predicates:
          - Path=/categories/**
          filters:
          - name: CircuitBreaker
            args:
              name: fallback
              fallbackUri: forward:/fallback
        - id: item_service
          uri: http://localhost:8083
          predicates:
          - Path=/items/**
          filters:
          - name: CircuitBreaker
            args:
              name: fallback
              fallbackUri: forward:/fallback
        - id: location_service
          uri: http://localhost:8084
          predicates:
          - Path=/locations/**
          filters:
          - name: CircuitBreaker
            args:
              name: fallback
              fallbackUri: forward:/fallback