server:
  port: 8086
spring:
  application:
    name: AUTH-SERVICE
  jpa:
    show-sql: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  profiles:
    active:
    - "@profileActive@"
  security:
    auth0:
      audience: https://inventorytracker.com
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-hd772wgr.us.auth0.com/
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: "*"